"""
Hayabusa 4.x execution wrapper for DFIR-AI.

This module is intentionally independent from the DFIR-AI report and IOC
pipelines. It only executes the external Hayabusa binary against a directory
containing EVTX files and produces a Hayabusa CSV result.
"""

from __future__ import annotations
import re
import argparse
import csv
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional


PROJECT_ROOT = Path(__file__).resolve().parents[1]

HAYABUSA_DIR = PROJECT_ROOT / "tools" / "hayabusa"
HAYABUSA_EXE = HAYABUSA_DIR / "hayabusa-4.0.0-win-x64.exe"

DEFAULT_DATASET = PROJECT_ROOT / "input" / "KAPE_OUTPUT"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "output" / "hayabusa"
DEFAULT_OUTPUT_FILE = DEFAULT_OUTPUT_DIR / "hayabusa_results.csv"
DEFAULT_HTML_REPORT = DEFAULT_OUTPUT_DIR / "hayabusa_report.html"


@dataclass
class HayabusaResult:
    success: bool
    output_path: Optional[Path]
    html_output_path: Optional[Path]
    evtx_files_found: int
    exit_code: int
    error: Optional[str] = None


def _find_evtx_files(dataset_path: Path) -> list[Path]:
    """Return EVTX files recursively, without modifying the evidence."""
    return [
        path
        for path in dataset_path.rglob("*")
        if path.is_file() and path.suffix.lower() == ".evtx"
    ]


def _read_hayabusa_csv_stats(output_path: Path) -> dict[str, int]:
    """
    Read the generated Hayabusa CSV and return REAL result statistics.

    The CSV generated by Hayabusa is the source of truth.
    Nothing is estimated or hardcoded here.
    """

    stats = {
        "detections": 0,
        "critical": 0,
        "high": 0,
        "medium": 0,
        "low": 0,
        "info": 0,
        "channels": 0,
        "rules": 0,
        "event_ids": 0,
        "computers": 0,
    }

    channels: set[str] = set()
    rules: set[str] = set()
    event_ids: set[str] = set()
    computers: set[str] = set()

    with output_path.open(
        "r",
        encoding="utf-8-sig",
        errors="replace",
        newline="",
    ) as handle:

        reader = csv.DictReader(handle)

        for row in reader:

            # Every CSV data row is one Hayabusa result.
            stats["detections"] += 1

            level = str(
                row.get("Level", "") or ""
            ).strip().lower()

            # Hayabusa 4.x uses "Med" for medium severity.
            severity_map = {
                "critical": "critical",
                "crit": "critical",

                "high": "high",

                "medium": "medium",
                "med": "medium",

                "low": "low",

                "info": "info",
                "informational": "info",
            }

            normalized_level = severity_map.get(level)

            if normalized_level:
                stats[normalized_level] += 1

            channel = str(
                row.get("Channel", "") or ""
            ).strip()

            if channel:
                channels.add(channel)

            rule_id = str(
                row.get("RuleID", "") or ""
            ).strip()

            if rule_id:
                rules.add(rule_id)

            event_id = str(
                row.get("EventID", "") or ""
            ).strip()

            if event_id:
                event_ids.add(event_id)

            computer = str(
                row.get("Computer", "") or ""
            ).strip()

            if computer:
                computers.add(computer)

    stats["channels"] = len(channels)
    stats["rules"] = len(rules)
    stats["event_ids"] = len(event_ids)
    stats["computers"] = len(computers)

    return stats


def generate_hayabusa_report(
    dataset_path: str | Path = DEFAULT_DATASET,
    output_path: str | Path = DEFAULT_OUTPUT_FILE,
    html_output_path: str | Path = DEFAULT_HTML_REPORT,
    hayabusa_executable: str | Path = HAYABUSA_EXE,
    log_callback: Optional[Callable[[str], None]] = None,
) -> HayabusaResult:

    dataset = Path(dataset_path).resolve()
    executable = Path(hayabusa_executable).resolve()
    output = Path(output_path).resolve()
    html_output = Path(html_output_path).resolve()

    # ------------------------------------------------------------
    # Validate evidence directory
    # ------------------------------------------------------------

    if not dataset.exists():
        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=0,
            exit_code=-1,
            error=f"Evidence directory does not exist: {dataset}",
        )

    if not dataset.is_dir():
        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=0,
            exit_code=-1,
            error=f"Evidence path is not a directory: {dataset}",
        )

    # ------------------------------------------------------------
    # Validate Hayabusa executable
    # ------------------------------------------------------------

    if not executable.exists():
        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=0,
            exit_code=-1,
            error=f"Hayabusa executable not found: {executable}",
        )

    # ------------------------------------------------------------
    # Discover EVTX files
    # ------------------------------------------------------------

    evtx_files = _find_evtx_files(dataset)

    if not evtx_files:
        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=0,
            exit_code=-1,
            error=f"No .evtx files found under: {dataset}",
        )

    output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ------------------------------------------------------------
    # Hayabusa command
    # ------------------------------------------------------------

    command = [
        str(executable),
        "dfir-timeline",
        "-d",
        str(dataset),
        "-w",
        "-o",
        str(output),
        "-H",
        str(html_output),
        "-t",
        "csv",
        "-C"
    ]

    if log_callback:

        log_callback("[PHASE] DISCOVERY")

        log_callback(
            f"[STAT] evtx_files_found={len(evtx_files)}"
        )

        log_callback(
            f"Hayabusa: found {len(evtx_files)} EVTX files."
        )

        log_callback("[PHASE] HAYABUSA_SCAN")

        log_callback(
            "Hayabusa: starting DFIR timeline scan..."
        )

    # ------------------------------------------------------------
    # Execute Hayabusa
    # ------------------------------------------------------------

    try:

        process = subprocess.Popen(
            command,
            cwd=str(HAYABUSA_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )

        assert process.stdout is not None

        for line in process.stdout:
            line = line.rstrip("\r\n")

            if not log_callback:
                continue

            # Keep the original Hayabusa output for the UI log.
            log_callback(line)

            # Hayabusa uses ANSI color/control sequences in its terminal output.
            # Strip them ONLY for machine-readable matching.
            clean_line = re.sub(
                r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])",
                "",
                line,
            ).strip()

            # ----------------------------------------------------
            # Real EVTX loaded count
            # ----------------------------------------------------
            if clean_line.startswith(
                "Evtx files loaded after channel filter:"
            ):
                try:
                    loaded = int(
                        clean_line.rsplit(":", 1)[1].strip()
                    )

                    log_callback(
                        f"[STAT] evtx_files_loaded={loaded}"
                    )

                except ValueError:
                    pass

            # ----------------------------------------------------
            # Scanning started
            # ----------------------------------------------------
            elif clean_line == "Scanning in progress. Please wait.":
                log_callback("[PHASE] SCANNING")

            # ----------------------------------------------------
            # Scanning finished
            # ----------------------------------------------------
            elif (
                "Scanning finished." in clean_line
            ):
                log_callback("[PHASE] SAVING_RESULTS")

        exit_code = process.wait()

    except OSError as exc:

        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=len(evtx_files),
            exit_code=-1,
            error=f"Could not start Hayabusa: {exc}",
        )

    except Exception as exc:

        return HayabusaResult(
            success=False,
            output_path=None,
            html_output_path=None,
            evtx_files_found=len(evtx_files),
            exit_code=-1,
            error=f"Hayabusa execution failed: {exc}",
        )

    # ------------------------------------------------------------
    # Verify process + CSV
    # ------------------------------------------------------------

    success = (
        exit_code == 0
        and output.exists()
        and html_output.exists()
    )

    if success:

        try:

            csv_stats = _read_hayabusa_csv_stats(
                output
            )

        except (
            OSError,
            csv.Error,
        ) as exc:

            if log_callback:

                log_callback(
                    "[PHASE] FAILED"
                )

                log_callback(
                    f"Could not read Hayabusa CSV: {exc}"
                )

            return HayabusaResult(
                success=False,
                output_path=output,
                html_output_path=(html_output if html_output.exists() else None),
                evtx_files_found=len(evtx_files),
                exit_code=exit_code,
                error=f"Could not read Hayabusa CSV: {exc}",
            )

        # --------------------------------------------------------
        # Send REAL statistics to the API
        # --------------------------------------------------------

        if log_callback:

            log_callback(
                f"[STAT] detections={csv_stats['detections']}"
            )

            log_callback(
                f"[STAT] critical={csv_stats['critical']}"
            )

            log_callback(
                f"[STAT] high={csv_stats['high']}"
            )

            log_callback(
                f"[STAT] medium={csv_stats['medium']}"
            )

            log_callback(
                f"[STAT] low={csv_stats['low']}"
            )

            log_callback(
                f"[STAT] info={csv_stats['info']}"
            )

            log_callback(
                f"[STAT] channels={csv_stats['channels']}"
            )

            log_callback(
                f"[STAT] rules={csv_stats['rules']}"
            )

            log_callback(
                f"[STAT] event_ids={csv_stats['event_ids']}"
            )

            log_callback(
                f"[STAT] computers={csv_stats['computers']}"
            )

            log_callback(
                f"Hayabusa: output saved to {output}"
            )

            log_callback(
                "[PHASE] COMPLETED"
            )

        return HayabusaResult(
            success=True,
            output_path=output,
            html_output_path=html_output,
            evtx_files_found=len(evtx_files),
            exit_code=exit_code,
        )

    # ------------------------------------------------------------
    # Hayabusa failed
    # ------------------------------------------------------------

    error = (
        f"Hayabusa exited with code {exit_code}."
        if exit_code != 0
        else
        f"Hayabusa reported success but output was not created: {output}"
    )

    if log_callback:

        log_callback(
            "[PHASE] FAILED"
        )

        log_callback(
            error
        )

    return HayabusaResult(
        success=False,
        output_path=(
            output
            if output.exists()
            else None
        ),
        html_output_path=(
            html_output
            if html_output.exists()
            else None
        ),
        evtx_files_found=len(evtx_files),
        exit_code=exit_code,
        error=error,
    )


def main() -> int:

    parser = argparse.ArgumentParser(
        description=(
            "Run Hayabusa independently against "
            "a KAPE/FastIR evidence directory."
        )
    )

    parser.add_argument(
        "-d",
        "--dataset",
        default=str(DEFAULT_DATASET),
        help="Evidence directory containing EVTX files.",
    )

    parser.add_argument(
        "-o",
        "--output",
        default=str(DEFAULT_OUTPUT_FILE),
        help="Destination Hayabusa CSV path.",
    )

    parser.add_argument(
        "--html-output",
        default=str(DEFAULT_HTML_REPORT),
        help="Destination Hayabusa HTML summary report path.",
    )

    parser.add_argument(
        "--exe",
        default=str(HAYABUSA_EXE),
        help="Path to the Hayabusa executable.",
    )

    args = parser.parse_args()

    result = generate_hayabusa_report(
        dataset_path=args.dataset,
        output_path=args.output,
        html_output_path=args.html_output,
        hayabusa_executable=args.exe,
        log_callback=print,
    )

    print()
    print("=" * 60)
    print("HAYABUSA RESULT")
    print("=" * 60)

    print(
        f"Success          : {result.success}"
    )

    print(
        f"EVTX files found : {result.evtx_files_found}"
    )

    print(
        f"Exit code        : {result.exit_code}"
    )

    print(
        f"CSV output       : "
        f"{result.output_path or 'N/A'}"
    )

    print(
        f"HTML report      : "
        f"{result.html_output_path or 'N/A'}"
    )

    if result.error:
        print(
            f"Error            : {result.error}"
        )

    return (
        0
        if result.success
        else 1
    )


if __name__ == "__main__":
    raise SystemExit(main())